# Generated by Django 5.2.11 on 2026-02-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReservationSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_date", models.DateField()),
                ("booking_count", models.IntegerField()),
                ("party_size_total", models.IntegerField()),
                ("actual_arrivals", models.IntegerField(default=0)),
                ("platform", models.CharField(max_length=50)),
            ],
        ),
    ]
