# Generated by Django 5.2.11 on 2026-02-11 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "google_place_id",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("location_name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "cuisine_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompetitorDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_observed", models.DateField()),
                ("deal_title", models.CharField(max_length=300)),
                (
                    "deal_source_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("impact_on_traffic", models.FloatField(blank=True, null=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="competitor_intel.competitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompetitorTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("estimated_visits", models.IntegerField()),
                ("traffic_score", models.IntegerField()),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_logs",
                        to="competitor_intel.competitor",
                    ),
                ),
            ],
        ),
    ]
