# Generated by Django 5.2.11 on 2026-02-09 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('metric_mae', models.FloatField()),
                ('metric_mape', models.FloatField()),
                ('model_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=100)),
                ('target_date', models.DateTimeField()),
                ('predicted_qty', models.FloatField()),
                ('confidence_upper', models.FloatField(blank=True, null=True)),
                ('confidence_lower', models.FloatField(blank=True, null=True)),
                ('training_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast.trainingrun')),
            ],
        ),
    ]
