# Generated by Django 5.2.11 on 2026-02-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_name', models.CharField(max_length=200)),
                ('impact_score', models.IntegerField(help_text='1-10 impact score')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
        ),
    ]
